In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../../Data/house_price/cleaning/train_cleaned_encoded.csv')
df.sample(20)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
451,452,20,3,62.0,70761,1,0,2,0,4,...,0,0,0,0,0,12,2006,8,4,280000
1055,1056,20,3,104.0,11361,1,3,3,0,4,...,0,0,189,0,0,5,2008,0,0,180000
675,676,160,3,24.0,2289,1,3,3,0,4,...,0,0,0,0,0,4,2009,8,4,148500
401,402,20,3,65.0,8767,1,0,3,0,4,...,0,0,0,0,0,7,2006,6,5,164990
1138,1139,20,3,69.0,9819,1,0,3,0,4,...,0,0,0,0,0,5,2009,8,4,196000
352,353,50,3,60.0,9084,1,3,3,0,4,...,0,0,0,0,0,3,2008,5,4,95000
1089,1090,120,1,37.0,3316,1,0,3,0,4,...,0,0,0,0,0,4,2006,8,4,197000
266,267,60,3,70.0,11207,1,0,1,0,2,...,0,0,0,0,0,6,2006,8,4,185000
511,512,120,3,40.0,6792,1,0,3,0,4,...,0,0,0,0,0,3,2006,6,5,202665
416,417,60,3,74.0,7844,1,3,3,0,4,...,0,0,0,0,0,3,2006,8,4,149500
525,526,20,1,62.0,7500,1,3,3,0,4,...,0,0,0,0,0,4,2006,8,4,176000
820,821,60,3,72.0,7226,1,0,3,0,1,...,0,0,0,0,0,6,2008,8,4,183000
438,439,30,3,40.0,4280,1,3,3,0,4,...,34,0,0,0,0,3,2007,8,4,90350
11,12,60,3,85.0,11924,1,0,3,0,4,...,0,0,0,0,0,7,2006,6,5,345000
921,922,90,3,67.0,8777,1,3,3,0,4,...,0,0,0,0,0,9,2008,8,4,145900
340,341,60,3,85.0,14191,1,3,3,0,4,...,0,0,0,0,0,4,2010,8,4,202900
389,390,60,3,96.0,12474,1,3,3,0,4,...,0,0,0,0,0,8,2008,6,5,426000
77,78,50,4,50.0,8635,1,3,3,0,4,...,0,0,0,0,0,1,2008,8,4,127000
304,305,75,4,87.0,18386,1,3,3,0,4,...,0,0,0,0,0,5,2008,8,4,295000
789,790,60,3,69.0,12205,1,0,2,0,4,...,0,0,0,0,0,7,2007,8,4,187500

In [4]:
df.info()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 77 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   int64
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   int64
 6   LotShape       1460 non-null   int64
 7   LandContour    1460 non-null   int64
 8   Utilities      1460 non-null   int64
 9   LotConfig      1460 non-null   int64
 10  LandSlope      1460 non-null   int64
 11  Neighborhood   1460 non-null   int64
 12  Condition1     1460 non-null   int64
 13  Condition2     1460 non-null   int64
 14  BldgType       1460 non-null   int64
 15  HouseStyle     1460 non-null   int64
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   int64
 21  RoofMatl       1460 non-null   int64
 22  Exterior1st    1460 non-null   int64
 23  Exterior2nd    1460 non-null   int64
 24  MasVnrType     1460 non-null   int64
 25  MasVnrArea     1460 non-null   float64
 26  ExterQual      1460 non-null   int64
 27  ExterCond      1460 non-null   int64
 28  Foundation     1460 non-null   int64
 29  BsmtQual       1460 non-null   int64
 30  BsmtCond       1460 non-null   int64
 31  BsmtExposure   1460 non-null   int64
 32  BsmtFinType1   1460 non-null   int64
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1460 non-null   int64
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   int64
 39  HeatingQC      1460 non-null   int64
 40  CentralAir     1460 non-null   int64
 41  Electrical     1460 non-null   int64
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   int64
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   int64
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    1460 non-null   int64
 57  GarageType     1460 non-null   int64
 58  GarageYrBlt    1460 non-null   float64
 59  GarageFinish   1460 non-null   int64
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1460 non-null   int64
 63  GarageCond     1460 non-null   int64
 64  PavedDrive     1460 non-null   int64
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  MiscVal        1460 non-null   int64
 72  MoSold         1460 non-null   int64
 73  YrSold         1460 non-null   int64
 74  SaleType       1460 non-null   int64
 75  SaleCondition  1460 non-null   int64
 76  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(74)
memory usage: 878.4 KB

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [5]:
# Total Luas Area
if all(col in df.columns for col in ['TotalBsmtSF', '1stFlrSF', '2ndFlrSF']):
    df['TotalLuasArea'] = df['TotalBsmtSF'] + df['1stFlrSF'] + df['2ndFlrSF']

# usia rumah 
if all(col in df.columns for col in ['YearBuilt', 'YrSold']):
    df['UsiaRumah'] = df['YrSold'] - df['YearBuilt']

# total kamar mandi
if all(col in df.columns for col in ['FullBath', 'HalfBath', 'BsmtFullBath', 'BsmtHalfBath']):
    df['TotalKamarMandi'] = df['FullBath'] + df['HalfBath'] + df['BsmtFullBath'] + df['BsmtHalfBath']

# rasio area rumah dengan area lot
if all(col in df.columns for col in ['GrLivArea', 'LotArea']):
    df['AreaRatio'] = df['GrLivArea'] / df['LotArea']

In [6]:
df[['TotalLuasArea', 'UsiaRumah', 'TotalKamarMandi', 'AreaRatio', 'SalePrice']].sample(20)

      TotalLuasArea  UsiaRumah  TotalKamarMandi  AreaRatio  SalePrice
1413           3688          4                3   0.167728     257000
641            2986          6                4   0.273617     226000
71             1690         25                2   0.111199     129500
939            3435         70                2   0.099751     244400
249            3588         49                3   0.013484     277000
495            1440         89                1   0.091382      34900
931            1850         44                2   0.101648     117500
144            3456         43                3   0.189890     125000
1157           2628          2                3   0.262747     230000
1038           1890         39                2   0.876712      97000
1194           2015         41                2   0.144383     158000
399            2642          3                3   0.190769     241000
783            2207         31                2   0.121965     165500
1392           1764         39                2   0.114825     123000
756            2634          2                3   0.164175     212000
165            1999         68                3   0.134079     127500
716            3272        117                2   0.236481     159500
241            1552         62                1   0.223196     110500
997            2884         39                2   0.123069     185000
204            2004         62                2   0.366857     110000

In [7]:
df.to_csv('../../Data/house_price/cleaning/train_engineering.csv', index=False)